### ISSUE TITLE
Deal 0 Damage

### ISSUE THREAD

**Issue by LeftCrosz** [Insprill/damage-indicator#9] opened 2022-10-08 09:31 UTC
I am using the latest DamageIndicators-1.3.2. It is not working well with latest WildStacker plugin. https://bg-software.com/wildstacker/
Details: If I have WildStacker's entities stacking enabled, whenever I killed the mobs it will show -0.00 Damage dealt.
![image](https://user-images.githubusercontent.com/40970486/194700635-04db086c-4c26-43c5-8c4c-0d3a9b80ad4e.png)

Details: If I have WildStacker's entities stacking disabled, whenever I killed the mobs it works like normal.
![image](https://user-images.githubusercontent.com/40970486/194700641-336201c2-afb3-487b-8361-52dc61749bfe.png)

**Comment by Insprill** [comment] 2022-10-10 12:43
It looks like this is an issue with how WildStacker handles stacked entity deaths. I've created an issue over there (https://github.com/BG-Software-LLC/WildStacker/issues/639) to track the root cause of this but as a temporary fix, I pushed a new dev build that simply ignores 0 damage so there just won't be an indicator. You can download it [here](https://github.com/Insprill/damage-indicator/actions/runs/3219373845).

**Comment by Insprill** [comment] 2022-10-13 19:47
Fixed with dev build 376 of WildStacker.

**Closed by Insprill** 2022-10-13 19:47 UTC
Labels: Bug: Confirmed
