### ISSUE TITLE
[Suggestion] Damage Indicators for MMOcore/MMOitems/Mythiclib

### ISSUE THREAD

**Issue by xuandattnvn1995** [Insprill/Damage-Indicator#7] opened 2022-09-09 17:06 UTC
Add crit/magic damage display function. i would like you can add some indicators of it.
https://www.spigotmc.org/resources/mythiclib.90306/
https://www.spigotmc.org/resources/mmocore.70575/
https://www.spigotmc.org/resources/mmoitems-premium.39267/

**Comment by Insprill** [comment] 2022-09-09 18:00
Duplicate of #6

**Closed** 2022-09-09 18:00 UTC
